name: Ingest PROD every 30m

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Shanghai
        run: |
          JSON=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=31.2304&longitude=121.4737&hourly=temperature_2m&timezone=UTC&past_days=1")
          I=$(jq '.hourly.time | length - 1' <<< "$JSON")
          TS=$(jq -r ".hourly.time[$I]" <<< "$JSON")
          TEMP=$(jq -r ".hourly.temperature_2m[$I]" <<< "$JSON")
          TSSEC=$(date -u -d "$TS" +%s)
          curl -s -X POST "$API_BASE/readings" \
            -H "Content-Type: application/json" \
            -H "x-ingest-key: $INGEST_KEY" \
            -d "{\"city\":\"shanghai\",\"timestamp\":$TSSEC,\"temp_c\":$TEMP,\"env_mode\":\"PROD\"}"
        env:
          API_BASE: ${{ secrets.API_BASE }}
          INGEST_KEY: ${{ secrets.INGEST_KEY }}

      - name: Berlin
        run: |
          JSON=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.405&hourly=temperature_2m&timezone=UTC&past_days=1")
          I=$(jq '.hourly.time | length - 1' <<< "$JSON")
          TS=$(jq -r ".hourly.time[$I]" <<< "$JSON")
          TEMP=$(jq -r ".hourly.temperature_2m[$I]" <<< "$JSON")
          TSSEC=$(date -u -d "$TS" +%s)
          curl -s -X POST "$API_BASE/readings" \
            -H "Content-Type: application/json" \
            -H "x-ingest-key: $INGEST_KEY" \
            -d "{\"city\":\"berlin\",\"timestamp\":$TSSEC,\"temp_c\":$TEMP,\"env_mode\":\"PROD\"}"
        env:
          API_BASE: ${{ secrets.API_BASE }}
          INGEST_KEY: ${{ secrets.INGEST_KEY }}

      - name: Rio
        run: |
          JSON=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=-22.9068&longitude=-43.1729&hourly=temperature_2m&timezone=UTC&past_days=1")
          I=$(jq '.hourly.time | length - 1' <<< "$JSON")
          TS=$(jq -r ".hourly.time[$I]" <<< "$JSON")
          TEMP=$(jq -r ".hourly.temperature_2m[$I]" <<< "$JSON")
          TSSEC=$(date -u -d "$TS" +%s)
          curl -s -X POST "$API_BASE/readings" \
            -H "Content-Type: application/json" \
            -H "x-ingest-key: $INGEST_KEY" \
            -d "{\"city\":\"rio\",\"timestamp\":$TSSEC,\"temp_c\":$TEMP,\"env_mode\":\"PROD\"}"
        env:
          API_BASE: ${{ secrets.API_BASE }}
          INGEST_KEY: ${{ secrets.INGEST_KEY }}
